services:
  - type: web
    name: leksaksinflation
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py createsuperuser --noinput --username admin --email admin@leksaksinflation.se"
    startCommand: "gunicorn toyinflation.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "mittlösen1234!"
      - key: DATABASE_URL
        value: "postgresql://brollopsplanner_db_user:wNhdgAtPjChqFC0SzFtJbr9S9itiW1cc@dpg-d8snfmjeo5us73enrllg-a/brollopsplanner_db"  # ← Klistra in din PostgreSQL URL här!